apiVersion: batch/v1
kind: Job
metadata:
  name: oci-buildah-job
  labels:
    jobgroup: oci-buildah-job
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: oci-buildah
    spec:
      containers:
      - name: oci-buildah
        image: abegolli/ocib-buildah:latest 
        command: ["ocictl"]
      restartPolicy: OnFailure
